Code comments and fixed error when compiling lightBase
lightBase error c2102 when compiling missing a l-value fixed by making local variable for reference